apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis-persistent
spec:
    selector:
        matchLabels:
            app: redis-persistent
    replicas: 1
    template:
        metadata:
            labels:
                app: redis-persistent
        spec:
            containers:
            - name: redis-persistent
              image: docker.cognigy.com:5000/redis-persistent:4.0.10-alpine
              resources:
                limits:
                    memory: "512Mi"
                    cpu: "500m"
                requests:
                    memory: "100Mi"
                    cpu: "200m"
              ports:
                - containerPort: 6379
              volumeMounts:
              - name: redis-data
                mountPath: /data
              - name: redis-password-config
                mountPath: /var/run/secrets/
              - name: redis-persistent-config
                mountPath: /var/run/config
            volumes:
            - name: redis-password-config
              secret:
                secretName: cognigy-redis-persistent-password
                items:
                - key: redis-persistent-password.conf
                  path: redis-password.conf
            - name: redis-persistent-config
              configMap:
                name: redis-persistent
            - name: redis-data
              persistentVolumeClaim:
                  claimName: redis-persistent-pvc
            imagePullSecrets:
            - name: cognigy-registry-token