{
 "title": "Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "RPC call duration by type (slower than 200ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(cognigy_rpc_duration_seconds_sum / cognigy_rpc_duration_seconds_count) > 0.200"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[30m])) * 100)"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  },
  {
   "title": "Traefik HTTP Status-Codes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_requests_total) by (code)"
    }
   ]
  },
  {
   "title": "Endpoint discarded messages total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 17 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "cognigy_endpoint_discarded_messages_total"
    }
   ]
  }
 ]
}