apiVersion: v1
kind: Service
metadata:
    name: service-endpoint
    labels:
        app: service-endpoint
    annotations:
        # Annotation our traefik reverse-proxy uses to enable
        # sticky-sessions. If you are not using traefik, this
        # annotation will do nothing.
        traefik.ingress.kubernetes.io/affinity: "true"
spec:
    ports:
        - name: service-endpoint
          port: 8000
          targetPort: 8000
          protocol: TCP
    selector:
        app: service-endpoint