{
 "title": "Traefik",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Endpoint 5XX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( increase( traefik_backend_requests_total{backend=\"<endpoint-url>/\", code=~\"5\\\\d\\\\d\"}[$__interval] ) )"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (traefik_backend_request_duration_seconds_sum{backend=\"<endpoint-url>/\"}) / sum (traefik_backend_request_duration_seconds_count{backend=\"<endpoint-url>/\"})"
    }
   ]
  },
  {
   "title": "Endpoint 4XX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( increase( traefik_backend_requests_total{backend=\"<endpoint-url>/\", code=~\"4\\\\d\\\\d\"}[$__interval] ) )"
    }
   ]
  },
  {
   "title": "Endpoint 2XX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( increase( traefik_backend_requests_total{backend=\"<endpoint-url>/\", code=~\"2\\\\d\\\\d\"}[$__interval] ) )"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "HTTP Status 5XX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( increase( traefik_backend_requests_total{protocol=\"http\", backend=\"<api-url>/\", code=~\"5\\\\d\\\\d\"}[$__interval] ) )"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 12 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum( traefik_backend_request_duration_seconds_sum{backend=\"<api-url>/\"} ) / sum( traefik_backend_request_duration_seconds_count{backend=\"<api-url>/\"} )"
    }
   ]
  },
  {
   "title": "HTTP Status 4XX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( increase( traefik_backend_requests_total{protocol=\"http\", backend=\"<api-url>/\", code=~\"4\\\\d\\\\d\"}[$__interval] ) )"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "RPC call type, flows-queue (slower than 200ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(cognigy_rpc_duration_seconds_sum{queue_name=\"flows-queue\"} / cognigy_rpc_duration_seconds_count{queue_name=\"flows-queue\"}) > 0.2"
    }
   ]
  },
  {
   "title": "RPC call duration by type (slower than 200ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(cognigy_rpc_duration_seconds_sum / cognigy_rpc_duration_seconds_count) > 0.200"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[30m])) * 100)"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Websockets, Traefik - service-endpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "traefik_backend_open_connections{backend=\"backend-cognigy-service-endpoint\", protocol=\"websocket\"}"
    }
   ]
  },
  {
   "title": "Websockets, Traefik - service-endpoints",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(traefik_backend_open_connections{backend=\"backend-cognigy-service-endpoint\", protocol=\"websocket\"})"
    }
   ]
  },
  {
   "title": "Endpoint discarded messages total",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "cognigy_endpoint_discarded_messages_total"
    }
   ]
  }
 ]
}
{
 "title": "Message-statistics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cognigy_message_counter[5m])"
    }
   ]
  }
 ]
}
{
 "title": "Stateful services",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "mongo-server, CPU container usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container=\"mongo-server\"}[5m]))"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{pod=~\"mongo-server-.*\"})"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"mongo-server-.*\"}"
    }
   ]
  },
  {
   "title": "mongo-server, Memory container usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{container=\"mongo-server\"})"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{pod=~\"mongo-server-.*\"})"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{pod=~\"mongo-server-.*\"})"
    }
   ]
  },
  {
   "title": "rabbitmq, CPU container usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container=\"rabbitmq\"}[5m]))"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{pod=~\"rabbitmq-.*\"})"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"rabbitmq-.*\"}"
    }
   ]
  },
  {
   "title": "rabbitmq, Memory container usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{container=\"rabbitmq\"})"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{pod=~\"rabbitmq-.*\"})"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{pod=~\"rabbitmq-.*\"})"
    }
   ]
  },
  {
   "title": "redis, CPU container usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container=\"redis\"}[5m]))"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{pod=~\"redis-.*\"})"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"redis-.*\"}"
    }
   ]
  },
  {
   "title": "redis, Memory container usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{container=\"redis\"})"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{pod=~\"redis-.*\"})"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{pod=~\"redis-.*\"})"
    }
   ]
  },
  {
   "title": "redis-persistent, CPU container usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container=\"redis-persistent\"}[5m]))"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{pod=~\"redis-persistent-.*\"})"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"redis-persistent-.*\"}"
    }
   ]
  },
  {
   "title": "redis-persistent, Memory container usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{container=\"redis-persistent\"})"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{pod=~\"redis-persistent-.*\"})"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{pod=~\"redis-persistent-.*\"})"
    }
   ]
  }
 ]
}