apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-profiles
spec:
  selector:
    matchLabels:
      app: service-profiles
  replicas: 1
  template:
    metadata:
      labels:
        app: service-profiles
    spec:
      containers:
        - name: service-profiles
          image: 'office-docker.cognigy.com:5000/service-profiles:bd19cd1836e0fd6981507282b60589c49a104b20'
          resources:
            requests:
              cpu: '0.1'
              memory: 60M
            limits:
              cpu: '0.1'
              memory: 75M
          envFrom:
            - configMapRef:
                name: cognigy-env
          volumeMounts:
            - name: rabbitmq-connection-string
              mountPath: /var/run/secrets/rabbitmqConnectionString
              subPath: rabbitmqConnectionString
            - name: mongodb-connection-string
              mountPath: /var/run/secrets/mongodbConnectionString
              subPath: mongodbConnectionString
            - name: redis-password
              mountPath: /var/run/secrets/redis-password.conf
              subPath: redis-password.conf
          livenessProbe:
            exec:
              command:
                - node
                - /opt/healthcheck.js
            failureThreshold: 3
            initialDelaySeconds: 90
            periodSeconds: 60
            timeoutSeconds: 10
      volumes:
        - name: rabbitmq-connection-string
          secret:
            secretName: cognigy-rabbitmq
            items:
              - key: connection-string
                path: rabbitmqConnectionString
        - name: mongodb-connection-string
          secret:
            secretName: cognigy-service-profiles
            items:
              - key: connection-string
                path: mongodbConnectionString
        - name: redis-password
          secret:
            secretName: cognigy-redis-password
      imagePullSecrets:
        - name: cognigy-registry-token
