apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-analytics-realtime
spec:
  selector:
    matchLabels:
      app: service-analytics-realtime
  replicas: 1
  template:
    metadata:
      labels:
        app: service-analytics-realtime
    spec:
      containers:
        - name: service-analytics-realtime
          image: 'office-docker.cognigy.com:5000/service-analytics-realtime:a861d8a13a92b918ed20b3ab0b9c2364b471855f'
          resources:
            requests:
              cpu: '0.1'
              memory: 60M
            limits:
              cpu: '0.1'
              memory: 75M
          envFrom:
            - configMapRef:
                name: cognigy-env
          volumeMounts:
            - name: rabbitmq-connection-string
              mountPath: /var/run/secrets/rabbitmqConnectionString
              subPath: rabbitmqConnectionString
            - name: redis-password
              mountPath: /var/run/secrets/redis-password.conf
              subPath: redis-password.conf
          livenessProbe:
            exec:
              command:
                - node
                - /opt/healthcheck.js
            failureThreshold: 3
            initialDelaySeconds: 90
            periodSeconds: 60
            timeoutSeconds: 10
      volumes:
        - name: rabbitmq-connection-string
          secret:
            secretName: cognigy-rabbitmq
            items:
              - key: connection-string
                path: rabbitmqConnectionString
        - name: redis-password
          secret:
            secretName: cognigy-redis-password
      imagePullSecrets:
        - name: cognigy-registry-token
