# SMTP email configuration
# - op: add
#   path: /data/SECURITY_SMTP_HOST
#   value: ""
# - op: add
#   path: /data/SECURITY_SMTP_PORT
#   value: "587"
# - op: add
#   path: /data/SECURITY_SMTP_USERNAME
#   value: ""
# - op: add
#   path: /data/SECURITY_SMTP_FROM
#   value: ""
# - op: add
#   path: /data/SECURITY_SMTP_CONNECTION_TYPE
#   value: "starttls"

# DNS names
- op: add
  path: /data/FRONTEND_BASE_URL_WITH_PROTOCOL
  value: "https://ui.chatbot-app-cognigy-platform.apps.esale-dev.prod.mobily.lan"
- op: add
  path: /data/BACKEND_BASE_URL_WITH_PROTOCOL
  value: "https://api.chatbot-app-cognigy-platform.apps.esale-dev.prod.mobily.lan"
- op: add
  path: /data/ENDPOINT_BASE_URL_WITH_PROTOCOL
  value: "https://endpoint.chatbot-app-cognigy-platform.apps.esale-dev.prod.mobily.lan"
- op: add
  path: /data/WEBCHAT_BASE_URL_WITH_PROTOCOL
  value: "https://webchat.chatbot-app-cognigy-platform.apps.esale-dev.prod.mobily.lan"
- op: add
  path: /data/ODATA_HOSTNAME
  value: "odata.chatbot-app-cognigy-platform.apps.esale-dev.prod.mobily.lan"
- op: add
  path: /data/ODATA_PROTOCOL
  value: "https"

# INTERNAL API for management ui
# - op: add
#   path: /data/INTERNAL_API_USERNAME
#   value: ""
# - op: add
#   path: /data/INTERNAL_API_PASSWORD
#   value: ""

# Enable max contact profile TTL in minutes 
- op: add
  path: /data/MAX_CONTACT_PROFILE_TTL_IN_MINUTES
  value: "43200"

# Enable max conversation TTL in minutes 
- op: add
  path: /data/MAX_CONVERSATION_TTL_IN_MINUTES
  value: "43200"

# Enable max conversation TTL in minutes 
- op: add
  path: /data/MAX_SESSION_STATE_TTL_IN_MINUTES
  value: "10080"